import os
from google import genai
from google.genai import types

def answer_question(context: str, question: str) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "System Configuration Error: Missing 'GEMINI_API_KEY' inside the execution environment."
    
    try:
        client = genai.Client(api_key=api_key)
        prompt = f"""
        You are an advanced academic Q&A agent. Answer the question precisely based ONLY on the provided context.
        If the answer cannot be confidently inferred from the context, leverage your generic academic knowledge base to answer accurately but indicate that it wasn't explicitly found in the context text.
        
        CONTEXT:
        {context}
        
        QUESTION:
        {question}
        """
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        return response.text if response.text else "No response generated by the model."
    except Exception as error:
        return f"Inference Error executing QnA Engine: {str(error)}"
